models/Deal.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
use yii\web\UploadedFile;

/**
 * This is the model class for table "deal".
 *
 * @property int $id
 * @property string $title
 * @property int $hotel_id
 * @property int $category_id
 * @property int $discount
 * @property string $description
 * @property string $terms
 * @property string $phone
 * @property string $email
 * @property string $website
 * @property string $facebook
 * @property string $instagram
 * @property string $rest_name
 * @property string $cuisine
 * @property int $status
 */
class Deal extends \yii\db\ActiveRecord
{
    public $oldimage,$oldimage2,$oldimage3,$imagefile,$imagefile2,$imagefile3,$city_id,$area_id,$cuisine,$hot_check,$leisure_deal,$subcategory;
    public $allowedImageSize = 1024000;
    public $allowedImageTypes=['jpg', 'jpeg', 'png', 'gif', 'JPG', 'JPEG', 'PNG', 'GIF'];
    public $additionalFields = [];

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'deal';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['category_id', 'discount', 'status'], 'integer'],
            [['description', 'terms'], 'string'],
            [['additionalFields','terms','hot_deal','hot_check','discount_description','hotel_id','cities','start_date','end_date','map_link','sub_category'], 'safe'],
            [['email'], 'email'],
            [['image','image2','image3'], 'file', 'extensions'=>implode(",",$this->allowedImageTypes)],
            [['title', 'phone', 'email', 'website', 'facebook', 'instagram', 'rest_name', 'cuisine'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'hotel_id' => 'Hotel ID',
            'category_id' => 'Category ID',
            'discount' => 'Discount',
            'description' => 'Description',
            'terms' => 'Terms',
            'phone' => 'Phone',
            'email' => 'Email',
            'website' => 'Website',
            'facebook' => 'Facebook',
            'instagram' => 'Instagram',
            'rest_name' => 'Rest Name',
            'cuisine' => 'Cuisine',
            'status' => 'Status',
        ];
    }
    /**
     * return html status
     */
    public function getTxtStatus()
    {
        return $this->status==1 ? '<span class="label label-success">Active</span>' : '<span class="label label-warning">Blocked</span>';
    }

    /**
     * @return image path
     */
    public function getImageSrc()
    {

        $image=Yii::$app->params['default_avatar'];
        if($this->image!=null && file_exists(Yii::$app->params['avatar_abs_path'].$this->image)){
            $image=Yii::$app->helperFunction->resize(Yii::$app->params['avatar_abs_path'], $this->image, 128, 128);
        }
        return $image;
    }
    /**
     * @return image 2 path
     */
    public function getImageSrc2()
    {

        $image=Yii::$app->params['default_avatar'];
        if($this->image2!=null && file_exists(Yii::$app->params['avatar_abs_path'].$this->image2)){
            $image=Yii::$app->helperFunction->resize(Yii::$app->params['avatar_abs_path'], $this->image2, 128, 128);
        }
        return $image;
    }

    /**
     * @return image 3 path
     */
    public function getImageSrc3()
    {

        $image=Yii::$app->params['default_avatar'];
        if($this->image3!=null && file_exists(Yii::$app->params['avatar_abs_path'].$this->image3)){
            $image=Yii::$app->helperFunction->resize(Yii::$app->params['avatar_abs_path'], $this->image3, 128, 128);
        }
        return $image;
    }

    /**
     * @inheritdoc
     */
    public function beforeValidate()
    {
        //Uploading image
        if(UploadedFile::getInstance($this, 'image')){
            $this->imagefile = UploadedFile::getInstance($this, 'image');
            // if no file was uploaded abort the upload
            if (!empty($this->imagefile) && file_exists($this->imagefile->tempName)) {
                $pInfo=pathinfo($this->imagefile->name);
                $ext = $pInfo['extension'];
                if (in_array($ext,$this->allowedImageTypes)) {
                    // Check to see if any PHP files are trying to be uploaded
                    $content = file_get_contents($this->imagefile->tempName);
                    if (preg_match('/\<\?php/i', $content)) {
                        $this->addError('image', Yii::t('app', 'Invalid file provided!'));
                        return false;
                    }else{
                        if (filesize($this->imagefile->tempName) <= $this->allowedImageSize) {
                            // generate a unique file name
                            $this->image = Yii::$app->controller->generateName().".{$ext}";
                        }else{
                            $this->addError('image', Yii::t('app', 'File size is too big!'));
                            return false;
                        }
                    }
                }else{
                    $this->addError('image', Yii::t('app', 'Invalid file provided!'));
                    return false;
                }
            }
        }
        if($this->image == null && $this->oldimage!= null){
            $this->image=$this->oldimage;
        }


        //Uploading image 2
        if(UploadedFile::getInstance($this, 'image2')){
            $this->imagefile2 = UploadedFile::getInstance($this, 'image2');
            // if no file was uploaded abort the upload
            if (!empty($this->imagefile2) && file_exists($this->imagefile2->tempName)) {
                $pInfo=pathinfo($this->imagefile2->name);
                $ext = $pInfo['extension'];
                if (in_array($ext,$this->allowedImageTypes)) {
                    // Check to see if any PHP files are trying to be uploaded
                    $content = file_get_contents($this->imagefile2->tempName);
                    if (preg_match('/\<\?php/i', $content)) {
                        $this->addError('image2', Yii::t('app', 'Invalid file provided!'));
                        return false;
                    }else{
                        if (filesize($this->imagefile2->tempName) <= $this->allowedImageSize) {
                            // generate a unique file name
                            $this->image2 = Yii::$app->controller->generateName().".{$ext}";
                        }else{
                            $this->addError('image2', Yii::t('app', 'File size is too big!'));
                            return false;
                        }
                    }
                }else{
                    $this->addError('image2', Yii::t('app', 'Invalid file provided!'));
                    return false;
                }
            }
        }
        if($this->image2 == null && $this->oldimage2!=null){
            $this->image2 = $this->oldimage2;
        }



        //Uploading image 3
        if(UploadedFile::getInstance($this, 'image3')){
            $this->imagefile3 = UploadedFile::getInstance($this, 'image3');
            // if no file was uploaded abort the upload
            if (!empty($this->imagefile3) && file_exists($this->imagefile3->tempName)) {
                $pInfo=pathinfo($this->imagefile3->name);
                $ext = $pInfo['extension'];
                if (in_array($ext,$this->allowedImageTypes)) {
                    // Check to see if any PHP files are trying to be uploaded
                    $content = file_get_contents($this->imagefile3->tempName);
                    if (preg_match('/\<\?php/i', $content)) {
                        $this->addError('image3', Yii::t('app', 'Invalid file provided!'));
                        return false;
                    }else{
                        if (filesize($this->imagefile3->tempName) <= $this->allowedImageSize) {
                            // generate a unique file name
                            $this->image3 = Yii::$app->controller->generateName().".{$ext}";
                        }else{
                            $this->addError('image3', Yii::t('app', 'File size is too big!'));
                            return false;
                        }
                    }
                }else{
                    $this->addError('image3', Yii::t('app', 'Invalid file provided!'));
                    return false;
                }
            }
        }
        if($this->image3 == null && $this->oldimage3 != null){
            $this->image3 = $this->oldimage3;
        }




        return parent::beforeValidate();
    }
    public function beforeSave($insert)
    {
        if(isset($this->id) && $this->id != null){

        }else{
            $this->created_date = date('Y-m-d');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function afterSave($insert, $changedAttributes)
    {
        if ($this->imagefile!== null && $this->image!=null) {
            if($this->oldimage!=null && $this->image!=$this->oldimage && file_exists(Yii::$app->params['avatar_abs_path'].$this->oldimage)){
                unlink(Yii::$app->params['avatar_abs_path'].$this->oldimage);
            }
            $this->imagefile->saveAs(Yii::$app->params['avatar_abs_path'].$this->image);
        }
        if ($this->imagefile2!== null && $this->image2!=null) {
            if($this->oldimage2!=null && $this->image2!=$this->oldimage2 && file_exists(Yii::$app->params['avatar_abs_path'].$this->oldimage2)){
                unlink(Yii::$app->params['avatar_abs_path'].$this->oldimage2);
            }
            $this->imagefile2->saveAs(Yii::$app->params['avatar_abs_path'].$this->image2);
        }

views/layouts/login.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use app\assetfiles\LoginAsset;
use AddToHomescreen\AddToHomescreenWidget;

LoginAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" sizes="16x16" href="<?= Yii::$app->params['siteUrl'] . 'images/icon-16x16.png'; ?>">
    <link rel="shortcut icon" sizes="196x196" href="<?= Yii::$app->params['siteUrl'] . 'images/icon-196x196.png'; ?>">
    <base href="<?= Yii::$app->params['siteUrl']?>">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode(Yii::$app->params['siteName'].' - '.$this->title) ?></title>
    <?php $this->head() ?>
    <?= AddToHomescreenWidget::widget() ;?>
</head>

<body class="">
<?php $this->beginBody() ?>
<div class="login-box-body"><?= $content;?></div>
<!--<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-top"><a href="#"><img src="<?/*= Yii::$app->params['siteUrl'].'/images/black-logo.jpg';*/?>" class="img-responsive center-block" /></a></div>
        <div class="col-lg-12 margin-top">
            <form id="" action="">
                <label for="inp" class="inp">
                    <input type="text" id="inp" placeholder="&nbsp;">
                    <span class="label">Hotel</span>
                    <span class="border"></span>
                </label>
                <label for="pass" class="inp">
                    <input type="password" id="inp" placeholder="&nbsp;">
                    <span class="label">Password</span>
                    <span class="border"></span>
                </label>
                <div class="col-lg-12 col-md-12 margin">
                    <input class="magic-checkbox" type="checkbox" name="layout" id="1" value="option">
                    <label for="1"></label>
                    <label class="pull-left text" for="1">
                        Remember Password.
                    </label>

                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <input type="submit" name="" value="login">
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>-->
<?php $this->endBody() ?>
</body>


<!--<body class="hold-transition login-page">
<?php /*$this->beginBody() */?>
<div class="login-box">
  <div class="login-logo">
    <?/*= Html::a('<img src="'.Yii::$app->params['siteUrl'].'/images/black-logo.jpg">',['site/login'])*/?>
  </div>
  <div class="login-box-body"><?/*= $content*/?></div>
</div>
<?php /*$this->endBody() */?>
</body>-->
</html>
<?php $this->endPage() ?>

views/layouts/main-admin.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\assetfiles\AppAsset;
use app\models\Announcement;
use app\widgets\Alert;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

AppAsset::register($this);
$this->registerJs('
	$(".sidebar-menu").tree();
');
?>
<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode(Yii::$app->params['siteName'] . ' - ' . $this->title) ?></title>
        <base href="<?= Yii::$app->params['siteUrl'] ?>"/>
        <?php $this->head() ?>
       <!-- <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
        <script>
            var OneSignal = window.OneSignal || [];
            OneSignal.push(function() {
                OneSignal.init({
                    appId: "e1f51b59-270a-4e39-aa36-db5d790478de",
                });
            });
        </script>-->
    </head>
    <body class="sidebar-mini skin-black-light">
    <?php $this->beginBody() ?>
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="<?= Yii::$app->params['siteUrl'] ?>" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>E</b>B</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><img style="height: 50px" src="<?= Yii::$app->params['siteUrl'] ?>/images/logo.jpg"
                                           class="img-responsive"/></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="<?= Yii::$app->params['siteUrl'] . Yii::$app->user->identity->imageSrc ?>"
                                     class="user-image" alt="User Image">
                                <span class="hidden-xs"><?= Yii::$app->user->identity->username ?></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="<?= Yii::$app->params['siteUrl'] . Yii::$app->user->identity->imageSrc ?>"
                                         class="img-circle" alt="User Image">
                                    <p>
                                        <?= Yii::$app->user->identity->username ?>
                                        <small>Member
                                            since <?= Yii::$app->formatter->asDate(Yii::$app->user->identity->created_at, "php:M. Y") ?></small>
                                    </p>
                                </li>
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <!--a href="#" class="btn btn-default btn-flat">Profile</a-->
                                    </div>
                                    <div class="pull-right">
                                        <?= Html::a('Sign out', ['site/logout-admin'], ['class' => 'btn btn-default btn-flat', 'data-method' => 'post']) ?>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <?php

        ?>
        <aside class="main-sidebar">
            <section class="sidebar">
                <ul class="sidebar-menu tree" data-widget="tree">
<?php if (Yii::$app->user->identity->user_type == 1 || Yii::$app->user->identity->user_type == 2) { ?>
                    <li class="<?php if (Yii::$app->controller->id == 'site') echo 'active'; ?>"><?= Html::a('<i class="fa fa-dashboard"></i> <span>Dashboard</span>', ['site/index-admin']) ?></li>
                    <li class="<?php if (Yii::$app->controller->id == 'hotel') echo 'active'; ?>"><?= Html::a('<i class="fa fa-list"></i> Manage Hotels', ['hotel/index']) ?></li>
                    <li class="<?php if (Yii::$app->controller->id == 'category') echo 'active'; ?>"><?= Html::a('<i class="fa fa-list"></i> Manage Category', ['category/index']) ?></li>
                    <li class="<?php if (Yii::$app->controller->id == 'deal') echo 'active'; ?>"><?= Html::a('<i class="fa fa-list"></i> Manage Deals', ['deal/index']) ?></li>
                    <li class="<?php if (Yii::$app->controller->id == 'city') echo 'active'; ?>"><?= Html::a('<i class="fa fa-list"></i> Manage Cities', ['city/index']) ?></li>
                    <li class="<?php if (Yii::$app->controller->id == 'area') echo 'active'; ?>"><?= Html::a('<i class="fa fa-list"></i> Manage Area', ['area/index']) ?></li>
                 <?php } ?>
                    <li><?= Html::a('<i class="fa fa-sign-out"></i> Logout', ['site/logout-admin'], ['data-method' => 'post']) ?></li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        <div class="content-wrapper" style="background-color: #ECF0F5 !important;">
            <?php
            $announcements = Announcement::find()->where(['and', ['<=', 'DATE(start_date)', date("Y-m-d")], ['>=', 'DATE(end_date)', date("Y-m-d")], ['trashed' => 0]])->asArray()->all();
            if ($announcements != null) {
                foreach ($announcements as $announcement) {
                    echo '
			<div style="padding: 15px;margin: 0;padding-bottom: 0;">
				<div class="callout callout-' . ($announcement['color_class'] != null && $announcement['color_class'] != '' ? $announcement['color_class'] : 'info') . '" style="margin: 0;">
					<i class="fa fa-bullhorn"></i>&nbsp;&nbsp;' . $announcement['heading'] . '<br />' . nl2br($announcement['descp']) . '
				</div>
			</div>';
                }
            }
            ?>
            <?php
            /* Yii::$app->user->identity->noticeText; */
            ?>
            <section class="content-header">
                <h1><?= $this->title . (isset($this->subHeading) ? '<small>' . $this->subHeading . '</small>' : '') ?></h1>
                <?= Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ]) ?>
            </section>
            <section class="content">
                <?= Alert::widget() ?>
                <?= $content ?>
            </section>
        </div>
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.4.0
            </div>
            <strong>Copyright &copy; <?= date("Y") . ' ' . Yii::$app->params['siteName'] ?>.</strong> All rights
            reserved.
        </footer>
    </div>
    <?php $this->endBody() ?>
    </body>
    </html>
<?php $this->endPage() ?>
<?php
yii\bootstrap\Modal::begin([
    'headerOptions' => ['id' => 'modalHeader'],
    'id' => 'modal',
    'size' => 'modal-lg',
    //keeps from closing modal with esc key or by clicking out of the modal.
    // user must click cancel or X to close
    'clientOptions' => ['backdrop' => 'static', 'keyboard' => true, 'tabindex' => false],
    'options' => ['tabindex' => false]
]);
echo "<div id='modalContent'><div style='text-align:center'><img src='" . Yii::getAlias('@web') . '/loader_gif.gif' . "'></div></div>";
yii\bootstrap\Modal::end();
?>

views/layouts/main-hotel.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\assetfiles\AppAsset;
use app\models\Announcement;
use app\widgets\Alert;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

AppAsset::register($this);
$this->registerJs('
	$(".sidebar-menu").tree();
');
?>
<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode(Yii::$app->params['siteName'] . ' - ' . $this->title) ?></title>
        <base href="<?= Yii::$app->params['siteUrl'] ?>"/>
        <?php $this->head() ?>
        <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
      <!--  <script>
            var OneSignal = window.OneSignal || [];
            OneSignal.push(function() {
                OneSignal.init({
                    appId: "e1f51b59-270a-4e39-aa36-db5d790478de",
                });
            });
        </script>-->
    </head>
    <body class="sidebar-mini skin-black-light">
    <?php $this->beginBody() ?>
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="<?= Yii::$app->params['siteUrl'] ?>" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>E</b>B</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><img style="height: 50px" src="<?= Yii::$app->params['siteUrl'] ?>/images/logo.jpg"
                                           class="img-responsive"/></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="<?= Yii::$app->params['siteUrl'] . Yii::$app->user->identity->imageSrc ?>"
                                     class="user-image" alt="User Image">
                                <span class="hidden-xs"><?= Yii::$app->user->identity->username ?></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="<?= Yii::$app->params['siteUrl'] . Yii::$app->user->identity->imageSrc ?>"
                                         class="img-circle" alt="User Image">
                                    <p>
                                        <?= Yii::$app->user->identity->username ?>
                                        <small>Member
                                            since <?= Yii::$app->formatter->asDate(Yii::$app->user->identity->created_at, "php:M. Y") ?></small>
                                    </p>
                                </li>
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <!--a href="#" class="btn btn-default btn-flat">Profile</a-->
                                    </div>
                                    <div class="pull-right">
                                        <?= Html::a('Sign out', ['site/logout-admin'], ['class' => 'btn btn-default btn-flat', 'data-method' => 'post']) ?>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <?php

        ?>
        <aside class="main-sidebar">
            <section class="sidebar">
                <ul class="sidebar-menu tree" data-widget="tree">
<?php if (Yii::$app->user->identity->user_type != 1 && Yii::$app->user->identity->user_type != 2) { ?>

                    <li class="<?php if (Yii::$app->controller->id == 'site' && Yii::$app->controller->action->id == 'index-hotelsettings') echo 'active'; ?>"><?= Html::a('<i class="fa fa-dashboard"></i> <span>Dashboard</span>', ['site/index-hotelsettings']) ?></li>
                    <li class="<?php if (Yii::$app->controller->id == 'hotel') echo 'active'; ?>"><?= Html::a('<i class="fa fa-list"></i> Manage Hotel Settings', ['hotel/update?id='.Yii::$app->user->identity->id]) ?></li>
                    <li class="<?php if (Yii::$app->controller->id == 'deal') echo 'active'; ?>"><?= Html::a('<i class="fa fa-list"></i> Manage Deals', ['deal/index']) ?></li>
    <!--<li class="<?php /*if (Yii::$app->controller->id == 'site' && Yii::$app->controller->action->id == 'index') echo 'active'; */?>"><?/*= Html::a('<i class="fa fa-sign-out"></i> <span>Back to Home</span>', ['site/index']) */?></li>-->
                 <?php } ?>
                    <li><?= Html::a('<i class="fa fa-sign-out"></i> Logout', ['site/logout-admin'], ['data-method' => 'post']) ?></li>
                   <!-- <li><?/*= Html::a('<i class="fa fa-sign-out"></i> Logout', ['site/logout'], ['data-method' => 'post']) */?></li>-->
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        <div class="content-wrapper" style="background-color: #ECF0F5 !important;">
            <?php
            $announcements = Announcement::find()->where(['and', ['<=', 'DATE(start_date)', date("Y-m-d")], ['>=', 'DATE(end_date)', date("Y-m-d")], ['trashed' => 0]])->asArray()->all();
            if ($announcements != null) {
                foreach ($announcements as $announcement) {
                    echo '
			<div style="padding: 15px;margin: 0;padding-bottom: 0;">
				<div class="callout callout-' . ($announcement['color_class'] != null && $announcement['color_class'] != '' ? $announcement['color_class'] : 'info') . '" style="margin: 0;">
					<i class="fa fa-bullhorn"></i>&nbsp;&nbsp;' . $announcement['heading'] . '<br />' . nl2br($announcement['descp']) . '
				</div>
			</div>';
                }
            }
            ?>
            <?php
            /* Yii::$app->user->identity->noticeText; */
            ?>
            <section class="content-header">
                <h1><?= $this->title . (isset($this->subHeading) ? '<small>' . $this->subHeading . '</small>' : '') ?></h1>
                <?= Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ]) ?>
            </section>
            <section class="content">
                <?= Alert::widget() ?>
                <?= $content ?>
            </section>
        </div>
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.4.0
            </div>
            <strong>Copyright &copy; <?= date("Y") . ' ' . Yii::$app->params['siteName'] ?>.</strong> All rights
            reserved.
        </footer>
    </div>
    <?php $this->endBody() ?>
    </body>
    </html>
<?php $this->endPage() ?>
<?php
yii\bootstrap\Modal::begin([
    'headerOptions' => ['id' => 'modalHeader'],
    'id' => 'modal',
    'size' => 'modal-lg',
    //keeps from closing modal with esc key or by clicking out of the modal.
    // user must click cancel or X to close
    'clientOptions' => ['backdrop' => 'static', 'keyboard' => true, 'tabindex' => false],
    'options' => ['tabindex' => false]
]);
echo "<div id='modalContent'><div style='text-align:center'><img src='" . Yii::getAlias('@web') . '/loader_gif.gif' . "'></div></div>";
yii\bootstrap\Modal::end();
?>