models/UserNote.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;

/**
 * This is the model class for table "{{%user_note}}".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $comment
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 * @property integer $trashed
 * @property string $trashed_at
 * @property integer $trashed_by
 */
class UserNote extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user_note}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id','comment'], 'required'],
            [['created_at', 'updated_at', 'trashed_at'], 'safe'],
            [['created_by', 'updated_by', 'trashed', 'trashed_by'], 'integer'],
            [['comment'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User'),
            'comment' => Yii::t('app', 'Note'),
            'created_at' => Yii::t('app', 'Created At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'trashed' => Yii::t('app', 'Trashed'),
            'trashed_at' => Yii::t('app', 'Trashed At'),
            'trashed_by' => Yii::t('app', 'Trashed By'),
        ];
    }
	
    /**
     * @inheritdoc
     */
	public function behaviors()
    {
        return [
			'timestamp' => [
				'class' => TimestampBehavior::className(),
				'attributes' => [
					ActiveRecord::EVENT_BEFORE_INSERT => ['created_at','updated_at'],
					ActiveRecord::EVENT_BEFORE_UPDATE => 'updated_at',
				],
				'value' => function($event) {
                    return date("Y-m-d H:i:s"); 
                },
			],
			'blameable' => [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],
		];
     }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
}

controllers/HotelController.php
<?php

namespace app\controllers;

use app\models\Area;
use app\models\City;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\User;
use app\models\UserSearch;
use yii\web\NotFoundHttpException;
use app\models\CategorySearch;
use app\models\DealSearch;

/**
 * Hotel Controller implements the CRUD actions for User model.
 */
class HotelController extends UserController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index','create','view','update','delete','getareasofcity'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
				'denyCallback' => function ($rule, $action) {
					if(Yii::$app->request->isAjax){
						throw new \yii\web\HttpException(401, Yii::t('app','Please login.'));
					}else{
						return $this->redirect(['site/login']);
					}
				}
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
		$this->checkAdmin();
        $this->layout = 'main-admin';
        $searchModel = new UserSearch();
		$searchModel->user_type = 0;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $session = Yii::$app->session;
        if (Yii::$app->user->identity->user_type == 1 || Yii::$app->user->identity->user_type == 2) {
            $this->checkAdmin();
            $this->layout = 'main-admin';
        }else if(Yii::$app->user->identity->user_type == 0 && $session->get('user_type_admin') == 3){
            $this->checkLogin();
            $this->layout = 'main-hotel';
        }
        //$this->layout = 'main-admin';
        $model = new User();
		$model->user_type = 0;
        if ($model->load(Yii::$app->request->post())) {
            if($model->save()){
            	Yii::$app->getSession()->addFlash('success', Yii::t('app','Information saved successfully'));
				return $this->redirect(['index']);
			}else{
				if($model->hasErrors()){
					foreach($model->getErrors() as $error){
						if(count($error)>0){
							foreach($error as $key=>$val){
								Yii::$app->getSession()->addFlash('error', $val);
							}
						}
					}
				}
			}
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $session = Yii::$app->session;
        if (Yii::$app->user->identity->user_type == 1 || Yii::$app->user->identity->user_type == 2) {
            $this->checkAdmin();
            $this->layout = 'main-admin';
        }else if(Yii::$app->user->identity->user_type == 0 && $session->get('user_type_admin') == 3){
            $this->checkLogin();
            $this->layout = 'main-hotel';
        }

		/*$this->checkAdmin();
        $this->layout = 'main-admin';*/
        $model = $this->findModel($id);
		$model->oldimage=$model->image;
        if ($model->load(Yii::$app->request->post())) {
            if($model->save()){
            	Yii::$app->getSession()->addFlash('success', Yii::t('app','Information saved successfully'));

                if (Yii::$app->user->identity->user_type == 1 || Yii::$app->user->identity->user_type == 2) {
                    return $this->redirect(['index']);
                }else{
                    return $this->redirect(['hotel/update?id='.Yii::$app->user->identity->id]);
                }



			}else{
				if($model->hasErrors()){
					foreach($model->getErrors() as $error){
						if(count($error)>0){
							foreach($error as $key=>$val){
								Yii::$app->getSession()->addFlash('error', $val);
							}
						}
					}
				}
			}
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }
    public function actionView($id)
    {

        $this->layout = 'main-admin';

        $searchModel = new DealSearch();
        $searchModel->hotel_id= $id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);




        return $this->render('view', [
            'model' => $this->findModel($id),
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionGetareasofcity()
    {
        if (Yii::$app->request->get()) {
            $city_id = Yii::$app->request->get('id');
            $area_id= '';

            if(Yii::$app->request->get('areaid')){
                $area_id = Yii::$app->request->get('areaid');
            }
            $package_data = City::findOne($city_id);
            $result = Area::find()->where(['city_id' => $city_id])->asArray()->all();
            $html = ' <option selected value="">Select Area</option>';
            $html2 = '';
            foreach ($result as $key => $res) {
                if(($area_id <> null) && ($res['id']== $area_id)){
                    $html .= ' <option selected value="'.$res['id'].'">'.$res['name'].'</option>';
                }
                else{
                    $html .= ' <option value="'.$res['id'].'">'.$res['name'].'</option>';
                }

            }
            echo json_encode(['options' =>$html]);
            exit;
        }
    }
}

views/hotel/_form.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\City;
use yii\helpers\Url;
use app\assetfiles\DatePickerAsset;

DatePickerAsset::register($this);

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
$this->registerJs('
	$(".dtpicker").datepicker({
		format: "yyyy-mm-dd",
		todayHighlight: true,
		endDate: new Date(),
	}).on("changeDate", function(e) {
		$(this).datepicker("hide");
	});
');

?>


<div class="user-form">
    <div class="box box-success">
        <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
        <div class="box-body">

            <div class="row">
                <div class="col-xs-12 col-sm-6"><?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?></div>
                <div class="col-xs-12 col-sm-6"><?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?></div>
                <div class="col-xs-12 col-sm-6"><?= $form->field($model, 'new_password')->textInput(['value' => $model->user_password]) ?></div>


                    <div class="col-xs-12 col-sm-6"><?= $form->field($model, 'admin_password')->textInput() ?></div>



                <div class="col-xs-12 col-sm-6"><?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?></div>
                <div class="col-xs-12 col-sm-6"><?= $form->field($model, 'mobile')->textInput(['maxlength' => true]) ?></div>
                <div class="col-xs-12 col-sm-6"><?= $form->field($model, 'city_id')->dropDownList(ArrayHelper::map(City::find()->where(['status' => 1, 'trashed' => 0])->orderBy('title')->asArray()->all(), 'id', 'title')) ?></div>
                <div class="col-xs-12 col-sm-6">
                    <div class="form-group field-user-area_id required has-success">
                        <label class="control-label" for="user-area_id">Area</label>
                        <select id="user-area_ids" class="form-control" name="User[area_id]" aria-required="true"
                                aria-invalid="false">
                            <option value="">Select area</option>
                        </select>

                        <div class="help-block"></div>
                    </div>
                    <input type="hidden" value="<?= $model->area_id; ?>" id="area_id_value">
                </div>
                <div class="col-xs-12 col-sm-6"><?= $form->field($model, 'status')->dropDownList(Yii::$app->params['statusArr']) ?></div>
            </div>
            <?php if ($model->imageSrc != null && $model->imageSrc != Yii::$app->params['default_avatar']) { ?>
                <div class="form-group">
                    <label class="control-label"><?= Yii::t('app', 'Old Image') ?></label>
                    <div><img src="<?= $model->imageSrc ?>" width="128"/></div>
                </div>
            <?php } ?>
            <?= $form->field($model, 'image')->fileInput() ?>

            <div class="row">
                <div class="col-xs-12 col-sm-6"><?= $form->field($model, 'address')->textarea(['rows' => 2]); ?></div>
            </div>
        </div>
        <div class="box">
            <div class="box-body">
                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
                    <?= Html::a(Yii::t('app', 'Cancel'), ['index'], ['class' => 'btn btn-default']) ?>
                </div>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>


    <?= $this->registerJs('


        var saved_area = $("#area_id_value").val();
        var current_city = $("#user-city_id").val();


        $.ajax({
            url:  "' . Url::base(true) . '/hotel/getareasofcity?id="+current_city+"&areaid="+saved_area,
            type: "GET",
            success : function(res){
                var obj = JSON.parse(res);
                $("#user-area_ids").html(obj.options);

            },
            error : function(data){
                console.log(data);
            }
        });




        $("body").on("change", "#user-city_id", function(e) {
            var city_id = $(this).val();
            $.ajax({
                url: "' . Url::base(true) . '/hotel/getareasofcity?id="+city_id,
                type: "GET",
                success : function(res){
                     var obj = JSON.parse(res);
                     $("#user-area_ids").html(obj.options);

                },
                error : function(data){
                    console.log(data);
                }
            });
        });
'); ?>

views/hotel/_note_item.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\UserRequestsDiscussion */
?>
<img src="<?= $model->createdBy->imageSrc?>" alt="user image" class="online">
<p class="message">
    <a href="#" class="name">
        <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> <?= Yii::$app->helperFunction->convertTime($model->updated_at)?></small>
        <?= $model->createdBy->username?>
    </a>
    <?= nl2br($model->comment)?>
</p>

views/hotel/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\DealSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="hotel-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>


    <?= $form->field($model, 'category_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/hotel/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'Create Hotel');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Members'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/hotel/index.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use app\widgets\CustomGridView;
use app\models\City;
use app\models\Package;
use app\models\Contracts;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Hotels');
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
    input[type=checkbox] {
        display: block;
    }
</style>
<div class="user-index">
    <?= \kartik\export\ExportMenu::widget([
        'dataProvider' => $dataProvider,
        'exportConfig' => [
            kartik\export\ExportMenu::FORMAT_PDF => false,
            kartik\export\ExportMenu::FORMAT_HTML => false,
            kartik\export\ExportMenu::FORMAT_CSV => false,
            kartik\export\ExportMenu::FORMAT_TEXT => false,
        ],
        'columns' => [
            //  ['class' => 'yii\grid\SerialColumn','headerOptions'=>['class'=>'noprint','style'=>'width:10px;'],],
            'id',
            'name',
            ['attribute'=>'username','value'=>function($model)

            {
                $result = \app\models\Deal::find()->where(['hotel_id' => $model->id])->asArray()->all();
                return count($result);


            },'label'=>'No. of Deals'],
            /*            'email:email',
                        'mobile',
                        ['attribute'=>'city_id','value'=>function($model){return $model->city->title;},'filter'=>ArrayHelper::map(City::find()->where(['status'=>1,'trashed'=>0])->orderBy('title')->asArray()->all(),'id','title')],*/

            ['format'=>'html','attribute'=>'status','value'=>function($model){return $model->txtStatus;},'filter'=>Yii::$app->params['statusArr']],
        ],
    ]);
    ?>



    <?= CustomGridView::widget([
		'create'=>true,
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
          //  ['class' => 'yii\grid\SerialColumn','headerOptions'=>['class'=>'noprint','style'=>'width:10px;'],],
            'id',
            'name',
            ['attribute'=>'username','value'=>function($model)

            {
                $result = \app\models\Deal::find()->where(['hotel_id' => $model->id])->asArray()->all();
               return count($result);


            },'label'=>'No. of Deals'],
/*            'email:email',
            'mobile',
            ['attribute'=>'city_id','value'=>function($model){return $model->city->title;},'filter'=>ArrayHelper::map(City::find()->where(['status'=>1,'trashed'=>0])->orderBy('title')->asArray()->all(),'id','title')],*/

            ['format'=>'html','attribute'=>'status','value'=>function($model){return $model->txtStatus;},'filter'=>Yii::$app->params['statusArr']],
            [
                'class' => 'yii\grid\ActionColumn',
                'header'=>Yii::t('app','Actions'),
                'headerOptions'=>['class'=>'noprint','style'=>'width:100px;'],
                'contentOptions'=>['class'=>'noprint text-right'],
                'template' => '{view} {update} {delete}',
                'buttons' => [
                    'view' => function ($url, $model) {
                        return Html::a('<i class="fa fa-folder"></i>', ['view','id'=>$model->id], [
                            'title' => Yii::t('app', 'View'),
                            'data-toggle'=>'tooltip',
                            'class'=>'btn btn-info btn-xs',
                        ]);
                    },
                    'update' => function ($url, $model) {
                        return Html::a('<i class="fa fa-edit"></i>', ['update','id'=>$model->id], [
                            'title' => Yii::t('app', 'Update'),
                            'data-toggle'=>'tooltip',
                            'class'=>'btn btn-success btn-xs',
                        ]);
                    },
                    'delete' => function ($url, $model) {
                        return Html::a('<i class="fa fa-remove"></i>', $url, [
                            'title' => Yii::t('app', 'Delete'),
                            'data-toggle'=>'tooltip',
                            'data-method'=>'post',
                            'data-confirm'=>Yii::t('app','Are you sure you want to delete this?'),
                            'class'=>'btn btn-danger btn-xs',
                        ]);
                    },
                ],
            ],
        ],
    ]); ?>
</div>

views/hotel/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'Update Hotel');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Hotel'), 'url' => ['index']];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="user-update">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/hotel/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ActiveForm;
use yii\widgets\ListView;
use app\widgets\CustomGridView;
use app\models\DealFields;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->username;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;


?>
<div class="user-view box">
    <div class="box-header with-border">
        <h3></h3>
        <div class="box-tools pull-right">
            <?= Html::a('<i class="fa fa-edit"></i>', ['update', 'id' => $model->id], ['class' => 'btn btn-box-tool', 'data-toggle' => 'tooltip', 'title' => 'Update']) ?>
            <?= Html::a('<i class="fa fa-trash"></i>', ['delete', 'id' => $model->id], ['class' => 'btn btn-box-tool', 'data-toggle' => 'tooltip', 'title' => 'Delete', 'data' => ['method' => 'post', 'confirm' => Yii::t('app', 'Are you sure you want to delete this?'),]]) ?>
            <?= Html::a('<i class="fa fa-times"></i>', ['index'], ['class' => 'btn btn-box-tool', 'data-toggle' => 'tooltip', 'title' => 'Back']) ?>
        </div>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-xs-12">
                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        ['attribute' => 'imageSrc', 'format' => ['image', ['width' => '100', 'height' => '100']]],
                        'name',
                        'username',
                        ['attribute' => 'city_id', 'value' => $model->city->title],
                        'email:email',
                        'mobile',
                        ['format' => 'html', 'attribute' => 'status', 'value' => function ($model) {
                            return $model->txtStatus;
                        }, 'filter' => Yii::$app->params['statusArr']],
                    ],
                ]) ?>
            </div>
        </div>
    </div>
    <div class="deal-index box">
        <div class="row">
        <div class="col-sm-12" >
            <h3 style="padding-left: 15px;"> Related Deals</h3>
        </div>
        </div>

        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

        <?= CustomGridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                /* ['class' => 'yii\grid\SerialColumn'],*/

                /* 'title',*/
                ['attribute'=>'rest_name','value'=>function($model){
                    if($model->category_id == 1){
                        $rest_name = DealFields::find()->where([
                            'deal_id' => $model->id,
                            'category_filed_id' => 1
                        ])->one();
                        if(isset($rest_name->value) &&  $rest_name->value <> null){
                            return $rest_name->value;
                        }else{
                            return $model->title;
                        }

                    }else if($model->category_id == 2){
                        $rest_name = DealFields::find()->where([
                            'deal_id' => $model->id,
                            'category_filed_id' => 3
                        ])->one();
                        if(isset($rest_name->value) &&  $rest_name->value <> null){
                            return $rest_name->value;
                        }else{
                            return $model->title;
                        }
                    }
                    return $model->name;
                }],
                /* ['attribute'=>'hotel_id','label'=>'Hotel','value'=>function($model){
                     return $model->user->name;
                 }],*/
                ['attribute' => 'category_id', 'label' => 'Category', 'value' => function ($model) {
                    return $model->category->title;
                }],

                ['format' => 'html', 'attribute' => 'status', 'value' => function ($model) {
                    return $model->txtStatus;
                }, 'filter' => Yii::$app->params['statusArr']],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'header' => Yii::t('app', 'Actions'),
                    'headerOptions' => ['class' => 'noprint', 'style' => 'width:100px;'],
                    'contentOptions' => ['class' => 'noprint text-right'],
                    'template' => '{view} {update}',
                    'buttons' => [
                        'view' => function ($url, $model) {
                            return Html::a('<i class="fa fa-folder"></i>', ['deal/view', 'id' => $model->id], [
                                'title' => Yii::t('app', 'View'),
                                'data-toggle' => 'tooltip',
                                'class' => 'btn btn-info btn-xs',
                            ]);
                        },
                        'update' => function ($url, $model) {
                            return Html::a('<i class="fa fa-edit"></i>', ['deal/update', 'id' => $model->id], [
                                'title' => Yii::t('app', 'Update'),
                                'data-toggle' => 'tooltip',
                                'class' => 'btn btn-success btn-xs',
                            ]);
                        },
                        /* 'delete' => function ($url, $model) {
                             return Html::a('<i class="fa fa-remove"></i>', $url, [
                                 'title' => Yii::t('app', 'Delete'),
                                 'data-toggle'=>'tooltip',
                                 'data-method'=>'post',
                                 'data-confirm'=>Yii::t('app','Are you sure you want to delete this?'),
                                 'class'=>'btn btn-danger btn-xs',
                             ]);
                         },*/
                    ],
                ],
            ],
        ]); ?>


    </div>
</div>
</div>

<!--<div class="box box-warning">
    <div class="box-header">
        <div class="note-form">
            <?php /*$form = ActiveForm::begin(); */ ?>
			<? /*= $form->field($modelNote, 'comment',['template'=>'
            <div class="input-group">
                <span class="input-group-addon">Note</span>
                {input}
                <span class="input-group-btn">
                    '.Html::submitButton(Yii::t('app', 'Post'), ['class' => 'btn btn-warning']).'
                </span>
            </div>
            {error}
            '])->textInput(['maxlength' => true]) */ ?>
            <?php /*ActiveForm::end(); */ ?>
        </div>
    </div>
	<?php
/*    echo ListView::widget( [
        'dataProvider' => $dataProvider,
        'id' => 'my-listview-id',
        'itemOptions' => ['class' => 'item'],
        'itemView' => '_note_item',
		'emptyText'=>'',
        'layout'=>"
            <div class=\"box-body chat\">{items}</div>
            <div class=\"box-footer\"><center>{pager}</center></div>
        ",
    ] );
    */ ?>
</div>-->